apiVersion: v1
kind: Pod
metadata:
  name: tsc003-test-tdmpc2
  namespace: ucsd-haosulab

spec:
  containers:
    - name: work-container
      image: nicklashansen/tdmpc2:1.0.0 # docker image
      # imagePullPolicy: Always
      command:
            - bash
            - -c
            - |
              source /usr/local/bin/_activate_current_env.sh
              git clone https://github.com/nicklashansen/tdmpc2.git
              echo "done setup"
              sleep infinity
      resources:
        requests:
          cpu: "10"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "10"
          memory: "16Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: tsc003-fast-vol
          mountPath: /tsc003-fast-vol
  volumes:
    - name: tsc003-fast-vol
      persistentVolumeClaim:
        claimName: tsc003-fast-vol
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
                - NVIDIA-GeForce-GTX-1080-Ti